- name: Ensure xmrig install dir exists
  ansible.builtin.file:
    path: "{{ xmrig_install_dir }}"
    owner: "{{ xmrig_user }}"
    group: "{{ xmrig_group }}"
    state: directory
    mode: '0755'
  become: true

- name: Download xmrig release
  ansible.builtin.get_url:
    url: "https://github.com/xmrig/xmrig/releases/download/v{{ xmrig_version }}/xmrig-{{ xmrig_version }}-linux-static-x64.tar.gz"
    dest: "{{ xmrig_install_dir }}/xmrig.tar.gz"
    mode: '0440'
  become: true
  when: not ansible_check_mode

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ xmrig_install_dir }}/xmrig.tar.gz"
    owner: "{{ xmrig_user }}"
    group: "{{ xmrig_group }}"
    mode: '0644'
  become: true
  become_user: "{{ xmrig_user }}"
  when: not ansible_check_mode

- name: Extract xmrig release
  ansible.builtin.unarchive:
    src: "{{ xmrig_install_dir }}/xmrig.tar.gz"
    dest: "{{ xmrig_install_dir }}"
    remote_src: true
    owner: "{{ xmrig_user }}"
    group: "{{ xmrig_group }}"
    mode: '0755'
    extra_opts:
      - --strip-components=1
  register: xmrig_extract
  become: true
  become_user: "{{ xmrig_user }}"
  when: not ansible_check_mode and xmrig_extract is changed or xmrig_extract is not defined
